### ISSUE TITLE
help pls)

### ISSUE THREAD

**Issue by Dorlander** [OneKeyToWin/OKTW2#3]
share pls LeagueSharp.Wrapper ))))

**Comment by SharpLeague** [comment]
Since you are actively working on leaguesharp scripts I think you have one.

**Comment by Dorlander** [comment]
> Since you are actively working on leaguesharp scripts I think you have one.


i lost this file(

**Comment by Dorlander** [comment]
would not ask ..

**Comment by Dorlander** [comment]
without it, I cannot compile OneKeyToWin_AIO_Sebby

**Comment by Dorlander** [comment]
https://pastebin.com/3u3uisPp i got this

**Comment by Dorlander** [comment]
nvm, just changed LeagueSharp.Wrapper to LeagueSharp and it worked
